# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-31 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roofs', '0003_auto_20170531_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='roof',
            name='good_view',
            field=models.BooleanField(default=False),
        ),
    ]
