# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-02 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roofs', '0004_roof_good_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roof',
            name='peak_wait_time',
        ),
        migrations.AddField(
            model_name='roof',
            name='short_wait',
            field=models.BooleanField(default=False),
        ),
    ]
