# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-04 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roofs', '0005_auto_20170602_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roof',
            name='good_view',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='roof',
            name='live_music',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='roof',
            name='pool',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='roof',
            name='short_wait',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='roof',
            name='touristy',
            field=models.NullBooleanField(default=None),
        ),
    ]
