# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-06 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roofs', '0006_auto_20170604_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roof',
            name='good_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='roof',
            name='live_music',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='roof',
            name='pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='roof',
            name='short_wait',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='roof',
            name='touristy',
            field=models.BooleanField(default=False),
        ),
    ]
